package ie.orangep.reLootplusplus.mixin;

import ie.orangep.reLootplusplus.config.model.rule.ChestAmountRule;
import ie.orangep.reLootplusplus.config.model.rule.ChestLootRule;
import ie.orangep.reLootplusplus.diagnostic.LegacyWarnReporter;
import ie.orangep.reLootplusplus.legacy.mapping.LegacyChestTypeMapper;
import ie.orangep.reLootplusplus.legacy.mapping.LegacyEntityIdFixer;
import ie.orangep.reLootplusplus.legacy.nbt.LenientNbtParser;
import ie.orangep.reLootplusplus.runtime.ChestLootRegistry;
import ie.orangep.reLootplusplus.runtime.RuntimeState;
import net.minecraft.item.Item;
import net.minecraft.loot.LootManager;
import net.minecraft.loot.LootPool;
import net.minecraft.loot.LootTable;
import net.minecraft.loot.entry.ItemEntry;
import net.minecraft.loot.function.SetCountLootFunction;
import net.minecraft.loot.function.SetNbtLootFunction;
import net.minecraft.loot.provider.number.ConstantLootNumberProvider;
import net.minecraft.loot.provider.number.UniformLootNumberProvider;
import net.minecraft.nbt.NbtCompound;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

import java.util.List;

/**
 * Intercepts {@link LootManager#getTable(Identifier)} so that synthetic
 * {@code re-lootplusplus:chest/*} loot table IDs (generated by
 * {@link LegacyChestTypeMapper} for unmapped custom addon chest types) return
 * a dynamically-built pool drawn from {@link ChestLootRegistry}.
 */
@Mixin(LootManager.class)
public abstract class LootManagerMixin {

    @Inject(method = "getTable", at = @At("RETURN"), cancellable = true)
    private void relootplusplus$customChestTable(Identifier id, CallbackInfoReturnable<LootTable> cir) {
        if (cir.getReturnValue() != LootTable.EMPTY) {
            return;
        }
        // Only handle re-lootplusplus:chest/* or lootplusplus:chest/* identifiers
        boolean isOurs = "re-lootplusplus".equals(id.getNamespace()) || "lootplusplus".equals(id.getNamespace());
        if (!isOurs || !id.getPath().startsWith("chest/")) {
            return;
        }

        LegacyChestTypeMapper mapper = RuntimeState.chestTypeMapper();
        ChestLootRegistry registry = RuntimeState.chestLootRegistry();
        if (registry == null) {
            return;
        }

        // Determine chest type name: prefer reverse lookup from mapper, else derive from path
        String chestType = mapper != null ? mapper.chestTypeFor(id) : null;
        if (chestType == null) {
            chestType = id.getPath().substring("chest/".length());
        }

        List<ChestLootRule> rules = registry.lootFor(chestType);
        if (rules.isEmpty()) {
            return;
        }

        LootTable table = buildTable(chestType, rules, registry, id);
        if (table != null) {
            cir.setReturnValue(table);
        }
    }

    private static LootTable buildTable(String chestType, List<ChestLootRule> rules,
                                        ChestLootRegistry registry, Identifier tableId) {
        LegacyWarnReporter reporter = RuntimeState.warnReporter();
        ChestAmountRule amount = registry.amountFor(chestType);
        int minRolls = amount != null ? amount.minItems() : 3;
        int maxRolls = amount != null ? amount.maxItems() : 9;

        LootPool.Builder pool = LootPool.builder()
            .rolls(UniformLootNumberProvider.create(minRolls, maxRolls));

        int added = 0;
        for (ChestLootRule rule : rules) {
            if (rule.weight() <= 0) {
                continue;
            }
            String normalizedId = LegacyEntityIdFixer.normalizeItemId(
                rule.itemId(), reporter,
                rule.sourceLoc() == null ? null : rule.sourceLoc().formatShort());
            Identifier itemId = Identifier.tryParse(normalizedId);
            if (itemId == null || !Registry.ITEM.containsId(itemId)) {
                continue;
            }
            Item item = Registry.ITEM.get(itemId);
            ItemEntry.Builder<?> entry = ItemEntry.builder(item).weight(rule.weight());

            if (rule.minCount() != rule.maxCount()) {
                entry.apply(SetCountLootFunction.builder(
                    UniformLootNumberProvider.create(rule.minCount(), rule.maxCount())));
            } else {
                entry.apply(SetCountLootFunction.builder(
                    ConstantLootNumberProvider.create(rule.minCount())));
            }

            if (rule.nbtRaw() != null && !rule.nbtRaw().isEmpty() && !"{}".equals(rule.nbtRaw())) {
                NbtCompound tag = LenientNbtParser.parseOrEmpty(
                    rule.nbtRaw(), reporter, rule.sourceLoc(), "LegacyNBT");
                if (tag != null) {
                    entry.apply(SetNbtLootFunction.builder(tag));
                }
            }

            pool.with(entry);
            added++;
        }

        if (added == 0) {
            return null;
        }
        return LootTable.builder()
            .pool(pool)
            .build();
    }
}
