package ie.orangep.reLootplusplus.legacy.mapping;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import ie.orangep.reLootplusplus.diagnostic.LegacyWarnReporter;
import ie.orangep.reLootplusplus.diagnostic.Log;
import ie.orangep.reLootplusplus.diagnostic.SourceLoc;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.util.Identifier;

import java.io.IOException;
import java.io.Reader;
import java.lang.reflect.Type;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collections;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

public final class LegacyChestTypeMapper {
    private static final String FILE_NAME = "legacy_chest_types.json";

    private final Map<String, String> mapping;
    private final LegacyWarnReporter warnReporter;
    /** Cache of resolved Identifiers (including synthetic ones for unmapped custom types). */
    private final ConcurrentHashMap<String, Identifier> resolved = new ConcurrentHashMap<>();
    /** Reverse map: synthetic Identifier → original chest type string. */
    private final ConcurrentHashMap<Identifier, String> syntheticReverse = new ConcurrentHashMap<>();

    public LegacyChestTypeMapper(LegacyWarnReporter warnReporter) {
        this.warnReporter = warnReporter;
        this.mapping = loadMapping();
    }

    /**
     * Resolves a legacy chest type name to a loot-table {@link Identifier}.
     * <p>
     * For types present in {@code legacy_chest_types.json} the configured target is returned.
     * For unmapped custom addon types a synthetic {@code re-lootplusplus:chest/<normalized>}
     * identifier is generated and cached, so the LootManager mixin can serve a dynamic pool.
     */
    public Identifier resolve(String chestType, SourceLoc loc) {
        return resolved.computeIfAbsent(chestType, ct -> {
            String target = mapping.get(ct);
            if (target != null) {
                Identifier id = Identifier.tryParse(target);
                if (id == null) {
                    warnReporter.warn("LegacyChestType", "bad mapping " + ct + " -> " + target, loc);
                    return null;
                }
                Log.trace("Legacy", "ChestType: {} → {}", ct, id);
                return id;
            }
            // Custom addon type: generate a deterministic synthetic identifier
            String normalized = toSnakePath(ct);
            Identifier synthetic = new Identifier("re-lootplusplus", "chest/" + normalized);
            syntheticReverse.put(synthetic, ct);
            warnReporter.warnOnce("LegacyChestType",
                "unmapped chest type '" + ct + "', using synthetic loot table " + synthetic, loc);
            return synthetic;
        });
    }

    /**
     * Returns the original chest type string for a synthetic identifier generated by this mapper,
     * or {@code null} if the identifier was not generated here.
     */
    public String chestTypeFor(Identifier id) {
        return syntheticReverse.get(id);
    }

    /**
     * Returns {@code true} if {@code id} is a synthetic identifier managed by this mapper.
     */
    public boolean isSynthetic(Identifier id) {
        return syntheticReverse.containsKey(id);
    }

    private Map<String, String> loadMapping() {
        Path configDir = FabricLoader.getInstance().getConfigDir();
        Path file = configDir.resolve(FILE_NAME);
        if (!Files.exists(file)) {
            return Collections.emptyMap();
        }
        Gson gson = new Gson();
        Type type = new TypeToken<Map<String, String>>() { }.getType();
        try (Reader reader = Files.newBufferedReader(file)) {
            Map<String, String> data = gson.fromJson(reader, type);
            if (data == null) {
                return Collections.emptyMap();
            }
            return data;
        } catch (IOException e) {
            return Collections.emptyMap();
        }
    }

    /** Converts a camelCase or dot-separated chest type name to a safe identifier path. */
    private static String toSnakePath(String name) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < name.length(); i++) {
            char c = name.charAt(i);
            if (c == '.' || c == '-' || c == ' ') {
                sb.append('_');
            } else if (Character.isUpperCase(c)) {
                if (i > 0) sb.append('_');
                sb.append(Character.toLowerCase(c));
            } else if (Identifier.isPathCharacterValid(c)) {
                sb.append(c);
            } else {
                sb.append('_');
            }
        }
        String result = sb.toString().toLowerCase(Locale.ROOT);
        // Collapse consecutive underscores
        while (result.contains("__")) {
            result = result.replace("__", "_");
        }
        return result.isEmpty() ? "unknown" : result;
    }
}
